export const initialProducts = [
  {
    id: 1,
    src: "/images/huawei-P30-lite_6Black.png",
    name: "HUAWEI P30 Lite 6/128GB Black",
    price: 257,
    brand: "Huawei",
    category: "Electronic",
    type: "Phone",
    material: "Plastic",
    design: "Modern",
    description:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit",
  },
  {
    id: 2,
    src: "/images/huawei-matepad.png",
    name: "Huawei MatePad 10.4 4/128Gb Wi-Fi Grey",
    price: 312,
    brand: "Huawei",
    category: "Electronic",
    type: "Tablet",
    material: "Plastic",
    design: "Modern",
    description:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit",
  },
  {
    id: 3,
    src: "/images/apple-watch.png",
    name: "Apple Watch SE (2022) GPS 40mm Starlight",
    price: 320,
    brand: "Huawei",
    category: "Electronic",
    type: "Smart-watch",
    material: "Aluminium",
    design: "Modern",
    description:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit ",
  },
  {
    id: 4,
    src: "/images/iphone12.png",
    name: "Apple iPhone 12 128GB Red",
    price: 804,
    brand: "Apple",
    category: "Electronic",
    type: "Phone",
    material: "Aluminium",
    design: "Modern",
    description:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit ",
  },
  {
    id: 5,
    src: "/images/macbook-pro.png",
    name: 'Laptop Apple MacBook Pro 16" M2 Pro 512GB 2023',
    price: 2980,
    brand: "Apple",
    category: "Electronic",
    type: "Laptop",
    material: "Aluminium",
    design: "Modern",
    description:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit ",
  },
];
